export const dummyUserData = [
  {
    id: 1,
    firstName: "Taida",
    lastName: "Kadrić",
    username: "tkadric",
    email: "tkadric@gmail.com",
    role: "Admin",
  },
  {
    id: 2,
    firstName: "Faruk",
    lastName: "Smajlović",
    username: "fsmile",
    email: "fsmile@gmail.com",
    role: "Admin",
  },
  {
    id: 3,
    firstName: "Kemal",
    lastName: "Lazović",
    username: "klazovic",
    email: "klazovic@gmail.com",
    role: "Admin",
  },
  {
    id: 4,
    firstName: "Lamija",
    lastName: "Lazović",
    username: "lamsla",
    email: "lamsla@gmail.com",
    role: "Shopper",
  },
  {
    id: 5,
    firstName: "Lamija",
    lastName: "Čizmić",
    username: "lasma",
    email: "lasma@gmail.com",
    role: "Shopper",
  },
  {
    id: 6,
    firstName: "Zdravko",
    lastName: "Čolić",
    username: "zdravkocolic",
    email: "zdravko@gmail.com",
    role: "Shopper",
  },
  {
    id: 7,
    firstName: "Božo",
    lastName: "Vrećo",
    username: "bvreco",
    email: "bozo@gmail.com",
    role: "Shopper",
  },
  {
    id: 8,
    firstName: "Rade",
    lastName: "Šerbedžija",
    username: "serbedzija",
    email: "ljubav@gmail.com",
    role: "Shopper",
  },
  {
    id: 9,
    firstName: "Oliver",
    lastName: "Dragojević",
    username: "odrago",
    email: "galeb@gmail.com",
    role: "Shopper",
  },
  {
    id: 10,
    firstName: "Mino",
    lastName: "Derlin",
    username: "dmerlin",
    email: "halima@gmail.com",
    role: "Shopper",
  },
  {
    id: 11,
    firstName: "Minka",
    lastName: "Derlin",
    username: "dminka",
    email: "minka@gmail.com",
    role: "Shopper",
  },
  {
    id: 12,
    firstName: "Ne",
    lastName: "Znam",
    username: "neznam",
    email: "ziziia@gmail.com",
    role: "Shopper",
  },
  {
    id: 13,
    firstName: "Adna",
    lastName: "Šestić",
    username: "a6ic",
    email: "asest@gmail.com",
    role: "Shopper",
  },
  {
    id: 14,
    firstName: "Amina",
    lastName: "Pojskić",
    username: "apojskic",
    email: "trncinincic@gmail.com",
    role: "Shopper",
  },
  {
    id: 15,
    firstName: "Medin",
    lastName: "Omerović",
    username: "medoom",
    email: "medo@gmail.com",
    role: "Shopper",
  },
  {
    id: 16,
    firstName: "Ema",
    lastName: "Muratović",
    username: "emmuratovic",
    email: "emmy@gmail.com",
    role: "Shopper",
  },
  {
    id: 17,
    firstName: "Amila",
    lastName: "Čizmić",
    username: "milociz",
    email: "milo@gmail.com",
    role: "Shopper",
  },
];
